# Generated by Django 4.0.2 on 2022-02-07 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='population',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
