# Generated by Django 4.0.2 on 2022-02-07 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_data_population'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name_plural': 'Data'},
        ),
        migrations.RenameField(
            model_name='data',
            old_name='population',
            new_name='solar_radiation',
        ),
    ]
