# Generated by Django 4.0.2 on 2022-02-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_data_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, null=True)),
                ('date', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='data',
            name='solar_radiation',
            field=models.FloatField(null=True),
        ),
    ]
