# Generated by Django 4.0.2 on 2022-02-22 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_search_alter_data_solar_radiation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
